name: oj_helper
description: "A new Flutter project."
publish_to: "none"
version: 2.9.1+1
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.0.0
  intl: ^0.20.2
  html: ^0.15.4
  webdriver: ^3.0.3
  provider: ^6.0.3
  flutter_distributor: ^0.4.5
  shared_preferences: ^2.0.11
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter
  window_manager: ^0.4.2
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  day_night_time_picker: "1.3.1"

flutter_launcher_icons:
  android: "ic_launch"
  image_path: "assets/images/ic_launch.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/ic_launch.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/platforms/

